UI/Models/ViewModel/ProductAddViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entities.Concrete;

namespace UI.Models.ViewModel
{
    public class ProductAddViewModel
    {        
        public int CategoryId { get; set; }
        public string ProName { get; set; }
        public short ProStock { get; set; }
        public decimal ProPrice { get; set; }
    }
}

UI/Models/ViewModel/ProductListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entities.Concrete;

namespace UI.Models.ViewModel
{
    public class ProductListModel
    {
        public int Id { get; set; }
        public int CategoryName { get; set; }
        public DateTime OrderDate { get; set; }
        public string Name { get; set; }
        public int Stock { get; set; }
        public decimal Price { get; set; }
    }
}

UI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Abstract;
using DataAccess.Abstract;
using Entities.Concrete;

namespace UI.Controllers
{
    public class CategoryController : Controller
    {
        ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            var result = _categoryService.GetAll().Data;
            return View(result);
        }

        [HttpPost]
        public ActionResult Add(Category category)
        {
            var model = new Category { CategoryName = category.CategoryName, Description = category.Description };
            var result = _categoryService.Add(model);
            if (!result.Success)
            {                
                ViewBag.ErrorMessage = result.Message;                
                return View("Index", _categoryService.GetAll().Data);  
            }
            ViewBag.SuccessMessage = result.Message;
            return View("Index", _categoryService.GetAll().Data);
        }
    }
}

UI/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Abstract;
using Entities.Concrete;
using UI.Models.ViewModel;

namespace UI.Controllers
{
    public class CustomerController : Controller
    {
        ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public ActionResult Index()
        {
            var model = _customerService.GetAll().Data;
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Customer model)
        {
            _customerService.Add(new Customer
            {
                CustomerId = model.CustomerId,
                CompanyName = model.CompanyName,                 
                City = model.City,                                 
            });

            return RedirectToAction("Index");
        }


    }
}

UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Abstract;
using Entities.Concrete;
using UI.Models.ViewModel;

namespace UI.Controllers
{
    public class ProductController : Controller
    {
        IProductService _productService;
        IOrderService _orderService;
        ICategoryService _categoryService;

        public ProductController(IProductService productService, IOrderService orderService, ICategoryService categoryService)
        {
            _productService = productService;
            _orderService = orderService;
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            var model = _productService.GetProductDetails().Data;            
            return View(model);
        }
        public ActionResult Add()
        {
            var categories = _categoryService.GetAll().Data;
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost]
        public ActionResult Add(ProductAddViewModel model)
        {
            _productService.Add(new Product
            {
                CategoryId = model.CategoryId,
                ProductName = model.ProName,
                UnitPrice = model.ProPrice,
                UnitsInStock = model.ProStock
            });
            // logicler gelicek , success result, error result

            return RedirectToAction("Index");
        }

    }
}

UI/Views/Category/Index.cshtml

@model List<Entities.Concrete.Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @ViewBag.ErrorMessage
    </div>
}
@if (ViewBag.SuccessMessage != null)
{
    <div class="alert alert-success">
        @ViewBag.SuccessMessage
    </div>
}

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.Description</td>
        </tr>
    }
</table>

@using (Html.BeginForm("Add", "Category", FormMethod.Post))
{
    <div class="form-group">
        <label for="Name">Name: </label>
        <input type="text" id="Name" name="CategoryName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Desc">Açıklama: </label>
        <input type="text" id="Desc" name="Description" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Ekle</button>
}




UI/Views/Customer/Add.cshtml

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Ekleme</h2>
@using (Html.BeginForm("Add", "Customer", FormMethod.Post))
{
    <div class="form-group">
        <label for="Name">Name: </label>
        <input type="text" id="Name" name="CompanyName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="City">Şehir: </label>
        <input type="text" id="City" name="City" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Id">Id: </label>
        <input type="text" id="Id" name="CustomerId" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Gönder</button>
}



UI/Views/Customer/Index.cshtml


@model List<Entities.Concrete.Customer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table">
    <tr>
        <th>No</th>
        <th>Ad</th>
        <th>Şehir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CustomerId</td>
            <td>@item.CompanyName</td>            
            <td>@item.City</td>

        </tr>
    }
</table>

<form method="get" action="@Url.Action("Add", "Customer")">
    <button type="submit" id="addProductBtn" class="btn btn-primary">Ekle</button>
</form>


UI/Views/Product/Add.cshtml

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @ViewBag.ErrorMessage
    </div>
}
<h2>Ürün Ekleme</h2>
@using (Html.BeginForm("Add", "Product", FormMethod.Post))
{
    <div class="form-group">
        <label for="ProName">Product Name: </label>
        <input type="text" id="ProName" name="ProName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="ProStock">Stock Amount: </label>
        <input type="text" id="ProStock" name="ProStock" class="form-control" />
    </div>
    <div class="form-group">
        <label for="ProPrice">Price: </label>
        <input type="text" id="ProPrice" name="ProPrice" class="form-control" />
    </div>
    <div class="form-group">
        @Html.Label("Kategori")
        @Html.DropDownList("CategoryId", (SelectList)ViewBag.Categories, "Bir kategori seçin", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Gönder</button>
}


UI/Views/Product/Index.cshtml

@model List<Entities.DTOs.ProductDetailDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.SuccessMessage != null)
{
    <div class="alert alert-success">
        @ViewBag.SuccessMessage
    </div>
}

<table class="table">
    <tr>
        <th>No</th>
        <th>Ürün Adı</th>
        <th>Kategori</th>
        <th>Ürün Adedi</th>
        <th>Ürün Fiyatı</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.CategoryName</td>
            <td>@item.Stock</td>
            <td>@item.Price</td>
        </tr>
    }
</table>

<form method="get" action="@Url.Action("Add", "Product")">
    <button type="submit" id="addProductBtn" class="btn btn-primary">Ekle</button>
</form>

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">                
                    <li>@Html.ActionLink("Categories", "Index", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>